name: Salom Dunyo Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tizim-tekshiruvi:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Salom berish
        run: echo "Salom, GitHub Actions muvaffaqiyatli ishlamoqda!"

      - name: Tizim haqida ma'lumot
        run: |
          echo "Operatsion tizim:"
          lsb_release -a
          echo "Hozirgi vaqt: $(date)"

      - name: Maxfiy ismni tekshirish
        env:
          MY_SECRET_NAME: ${{ secrets.FOYDALANUVCHI_NOMI2 }}
        run: |
          echo "Hozir maxfiy ismni chiqaramiz..."
          echo "Mening ismim: $MY_SECRET_NAME"
